export enum SupportProperties {
  OPACITY = "opacity",
  COLOR = "color",
  BACKGROUND_COLOR = "background-color",
  WIDTH = "width",
  HEIGHT = "height",
  MARGIN = "margin",
  PADDING = "padding",
  TRANSFORM = "transform",
  TRANSFORM_ORIGIN = "transform-origin",
  BORDER_RADIUS = "border-radius",
  BORDER_WIDTH = "border-width",
  BORDER_COLOR = "border-color",
  // TOP = "top",
  // LEFT = "left",
  // RIGHT = "right",
  // BOTTOM = "bottom",
  // OUTLINE = "outline",
  ANIMATION_TIMING_FUNCTION = "animation-timing-function",
}

export const cssPropertiesLabelMapping = Object.freeze({
  [SupportProperties.OPACITY]: "Opacity",
  [SupportProperties.COLOR]: "Color",
  [SupportProperties.BACKGROUND_COLOR]: "Background Color",
  [SupportProperties.WIDTH]: "Width",
  [SupportProperties.HEIGHT]: "Height",
  [SupportProperties.MARGIN]: "Margin",
  [SupportProperties.PADDING]: "Padding",
  [SupportProperties.TRANSFORM]: "Transform",
  [SupportProperties.TRANSFORM_ORIGIN]: "Transform Origin",
  // [SupportProperties.TRANSLATE]: "Translate",
  // [SupportProperties.SCALE]: "Scale",
  // [SupportProperties.ROTATE]: "Rotate",
  [SupportProperties.BORDER_RADIUS]: "Border Radius",
  [SupportProperties.BORDER_WIDTH]: "Border Width",
  [SupportProperties.BORDER_COLOR]: "Border Color",
  // [SupportProperties.TOP]: "Top",
  // [SupportProperties.LEFT]: "Left",
  // [SupportProperties.RIGHT]: "Right",
  // [SupportProperties.BOTTOM]: "Bottom",
  // [SupportProperties.OUTLINE]: "Outline",
  [SupportProperties.ANIMATION_TIMING_FUNCTION]: "Timing",
});
